name: CI.unit-tests
run-name: ${{ github.actor }} is running CI unit tests
on: 
  workflow_dispatch:
  push:
    branches: [dev,main]

env:
  CI_COMMIT_TAG: 3.16.2
  CI_PROJECT_DIR: .
  FEATURES: 'telio drop'
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  test-go:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nordsecurity/nordvpn-linux/builder:1.0.0
      options: --user root
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Test go
        run: |
          git config --global --add safe.directory '*'
          git version
          $CI_PROJECT_DIR/ci/test.sh
  test-cgo:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nordsecurity/nordvpn-linux/builder:1.0.0
      options: --user root
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Test cgo
        run: |
          git config --global --add safe.directory '*'
          git version
          $CI_PROJECT_DIR/ci/test.sh full
